###
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "owner_id": "A",
  "name": "Apple",
  "price": 1.60
}

###
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "owner_id": "A",
  "name": "Orange",
  "price": 1.80
}

###
GET http://localhost:8080/api/products/397a950a-f65a-4db5-9f3e-de1a43ea3dd0
